


@startuml
package "Authentication Agent" {

    class AuthenticationDisplay <<Presentation>> {
        +displayMessage() : void
        +login() : boolean
    }

    class AuthenticationController <<Control>> {
        +authenticate() : TOKEN
        -storeToken(TOKEN) : boolean
        -getToken() : TOKEN
        +validateToken() : boolean
    }

    class AuthenticationModel <<Abstraction>> {
        -authToken : TOKEN
        +getToken() : TOKEN
        +setToken() : boolean
    }

    ' abstract class AuthenticationMessage {
    '     +displayMessage() : void
    ' }

    ' class AuthenticationSuccessMessage {
    '     -message : String
    '     +displayMessage() : void
    ' }

    ' class AuthenticationErrorMessage {
    '     -message : String
    '     +displayMessage() : void
    ' }

    ' AuthenticationSuccessMessage --|>AuthenticationMessage
    ' AuthenticationErrorMessage --|> AuthenticationMessage

    AuthenticationDisplay <--> AuthenticationController
    ' AuthenticationDisplay ..> AuthenticationMessage

    AuthenticationController --> AuthenticationModel
}

package "Data Agent" {

    class DataValidatorController <<Control>> {
        +validateData() : boolean
        +forwardValidatedData() : boolean
    }

    class DataValidatorModel <<Abstraction>> {
        +checkDataFormat() : boolean
        +checkDataRange() : boolean
    }
     class DataValidatorDisplay <<Presentation>> {
        -displayString: String
        +displayMessage() : void
    }

    class DataController <<Control>> {
        -currentView : DataViews
        +storeData() : boolean
        +getData() : JSON
        -filterData() : JSON
        -authenticate() : boolean
        -fetchData() : JSON
    }

    class DataModel <<Abstraction>> {
        -dataDB : EnvironmentalDataDatabase
        +storeData() : boolean
        +fetchData() : JSON
        +filterData() : JSON
    }

    abstract class DataDisplay <<Presentation>> {
        -displayString: String
        +displayMessage() : void
    }

    class ReadOnlyApi <<Presentation>> {
        +displayMessage() : void
    }

    class WebDashBoard <<Presentation>> {
        +displayMessage() : void
    }

    enum DataViews {
        PUBLIC
        PRIVATE
    }

    WebDashBoard --|> DataDisplay
    ReadOnlyApi --|> DataDisplay

    DataDisplay <--> DataController

    DataController --> DataModel
    DataController *--> DataViews
    DataController --> AuthenticationController
    DataController <--> DataValidatorController

    DataValidatorController --> DataValidatorModel
    DataValidatorController <--> DataValidatorDisplay

}



package "Alert Agent" {

    class AlertDisplay <<Presentation>> {
        +viewAlerts() : JSON
        +modifyAlerts() : boolean
        +displayMessage() : void
    }

    class AlertController <<Control>> {
        +viewAlerts() : JSON
        -verifyRole() : boolean
        +modifyAlerts() : boolean
        -triggerAlert() : void
        -adaptiveAlertThresholds() : void
    }

    class AlertModel <<Abstraction>> {
        -alertInfoDB : AlertInfoDatabase
        -alertThresholdDB : AlertThresholdDatabase
        -monitorValues() : void
        +viewAlerts() : JSON
        +modifyAlerts() : boolean
    }

    class AlertInfoDatabase {
        +getAlerts(): JSON
    }

    class AlertThresholdDatabase {
        +getAlertThreshold(): JSON

    }

    ' abstract class AlertDisplayMessage <<Presentation>> {
    '     +displayMessage() : void
    ' }

'     class AlertSuccessMessage <<Presentation>> {
'         -message : String
'         +displayMessage() : void
'     }

'     class AlertErrorMessage <<Presentation>> {
'         -message : String
'         +displayMessage() : void
' }

    ' AlertErrorMessage --|>  AlertDisplayMessage
    ' AlertSuccessMessage --|> AlertDisplayMessage
    ' AlertDisplay *-- AlertDisplayMessage


    AlertDisplay <--> AlertController

    AlertController --> AlertModel

    

    AlertModel *-- AlertInfoDatabase
    AlertModel *-- AlertThresholdDatabase
    DataController <-- AlertController
}




package "Subscription Agent" {

    ' abstract class SubscriptionStatusDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }
    ' class SubscriptionSuccessDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }
    ' class SubscriptionFailedDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }

    class SubscriptionDisplay <<Presentation>> {
        +subscribe() : boolean
        +displayMessage() : void
    }

    class SubscriptionController <<Control>> {
        +notifySubscribers() : void
        +subscribe() : boolean
        -authenticate() : boolean
    }

    class SubscriptionModel <<Abstraction>> {
        -subscriptionsDB : SubscriptionsDatabase
        +subscribe() : boolean
        +getSubscribers() : JSON
    }

    ' SubscriptionSuccessDisplay --|> SubscriptionStatusDisplay
    ' SubscriptionFailedDisplay --|> SubscriptionStatusDisplay


    SubscriptionDisplay <--> SubscriptionController
    ' SubscriptionDisplay *.. SubscriptionStatusDisplay

    SubscriptionController --> SubscriptionModel
    SubscriptionController --> AuthenticationController

}


package "Log Agent" {

    ' abstract class LogStatusDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }
    ' class LogSuccessDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }
    ' class LogFailedDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }

    class LogDisplay <<Presentation>> {
        +viewLogs() : JSON
        +displayMessage() : void
    }

    class LogController <<Control>>  {
        +viewLogs() : JSON
        -authenticate() : boolean
        -verifyRole() : boolean
        +logEvent(Event) : boolean
    }

    class LogModel <<Abstraction>> {
        -logsDB : LogsDatabase
        +viewLogs() : JSON
        +logEvent(Event) : boolean
    }

    ' LogSuccessDisplay --|> LogStatusDisplay
    ' LogFailedDisplay --|> LogStatusDisplay

    LogDisplay <--> LogController
    ' LogDisplay *..> LogStatusDisplay

    LogController --> LogModel
    LogController --> AuthenticationController

}


package "RBAC Agent" {

    ' abstract class RBACStatusDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }
    ' class RBACSuccessDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }
    ' class RBACFailedDisplay <<Presentation>> {
    '     -displayString: String
    '     +displayMessage() : void
    ' }

    class RBACDisplay <<Presentation>> {
        +viewRoles() : JSON
        +updateRole(PersonID, NewRole) : boolean
        +displayMessage() : void
    }

    class RBACController <<Control>> {
        +viewRoles() : JSON
        +updateRole(PersonID, NewRole) : boolean
        -authenticate() : boolean
        +verifyRole() : boolean
    }

    class RBACModel <<Abstraction>> {
        -rbacDB : RBACDatabase
        +viewRoles() : JSON
        +updateRole(PersonID, NewRole) : boolean
    }

    ' RBACSuccessDisplay --|> RBACStatusDisplay
    ' RBACFailedDisplay --|> RBACStatusDisplay

    RBACDisplay <--> RBACController
    ' RBACDisplay ..> RBACStatusDisplay

    RBACController --> RBACModel
    RBACController --> AuthenticationController

}

    AlertController <--> RBACController
    AlertController <--> SubscriptionController
    RBACController --> LogController 
    AlertController --> LogController 
    SubscriptionController --> LogController 

@enduml
