@startuml
title Detailed Class Diagram

class DataValidator {
    +validateData() : boolean
    -storeData() : boolean
}

class DataController {
    -storeData : DataViews
    +storeData() : boolean
    +getData() : JSON
    -filterData() : JSON
    -authenticate() : boolean
    -fetchData() : JSON
    - dataDB : Enviroment Data Database
}

abstract DataDisplay{
    + displayMessage() : void
    + dataType: DataViews
    +getData() : JSON
    +outputData() : JSON
}

class ReadOnlyApi{
    +getData() : JSON
}

class WebDashBoard{
    +getData() : JSON
}

WebDashBoard --|> DataDisplay
ReadOnlyApi --|> DataDisplay
DataDisplay ..> DataController 


interface DisplayStatusMessage{
    +displayMessage() : void
}

class ErrorMessage{
    -message: String
    +displayMessage() : void
}
class SuccessMessage{
    -message: String
    +displayMessage() : void
}
class TimeoutMessage{
    -message: String
    +displayMessage() : void
}
TimeoutMessage ..|> DisplayStatusMessage
SuccessMessage ..|> DisplayStatusMessage
ErrorMessage ..|> DisplayStatusMessage

enum DataViews {
    PUBLIC
    PRIVATE
}



' authentication
class AuthenticationController {
    +authenticate() : boolean
    -displayMessage() : void
    -authToken : <TOKEN>
}
interface AuthenticationMessage{
    +displayMessage() : void
}
class AuthenticationSuccessMessage{
    -message: String
    +displayMessage() : void
}
class AuthenticationErrorMessage{
    -message: String
    +displayMessage() : void
}
AuthenticationSuccessMessage --|> AuthenticationMessage
AuthenticationErrorMessage --|> AuthenticationMessage

DataValidator ..> DataController 
DataDisplay "1" *-- "1" DataViews 
DataDisplay ..> DisplayStatusMessage 
DataController ..> AuthenticationController 
AuthenticationController ..> AuthenticationMessage 

class AlertController {
    -alertInfoDB: Database
    -alertThresholdDB: Database
    +viewAlerts():JSON
    -authenticate() : boolean
    -verifyRole(): boolean
    +modifyAlerts(): boolean
    -triggerAlert(): void
    -displayMessage(): void
    -logEvent() : boolean
}
AlertController ..> DisplayStatusMessage 
AlertController ..> AuthenticationController 

class SubscriptionController {
    -subscriptionsDB: Database
    +notifySubscribers(): void
    +subscribe(): boolean
    -authenticate() : boolean
    -logEvent() : boolean
}
AlertController ..> SubscriptionController 

class LogController {
    -logsDB: Database
    +viewLogs() : JSON
    -authenticate() : boolean
    -verifyRole(): boolean
    +logEvent() : boolean
}
AlertController ..> LogController 
SubscriptionController ..> LogController 

class RBACController {
    -rbacDB: Database
    +viewRoles() : List<Role>
    +updateRole(PersonID,NewRole) : boolean
    -authenticate() : boolean
    +logEvent() : boolean
}
AlertController ..> RBACController 
LogController ..> RBACController 





@enduml