@startuml

skinparam State {
  BackgroundColor white
  BorderColor black
}

[*] --> viewLogs
viewLogs : user_information
viewLogs : logs
viewLogs : ----\n

viewLogs --> logSuccess : Success
logSuccess : success_message
logSuccess : ----
logSuccess : display success message
logSuccess : display logs
logSuccess --> [*]

viewLogs --> logError : Error
logError : error_message
logError : timeout_message
logError : ----
logError : display error message
logError --> viewLogs

@enduml