' BE5. View audit logs
@startuml

hide footbox

skinparam ParticipantBorderColor transparent
skinparam ParticipantBackgroundColor transparent
skinparam ActorBorderColor transparent
skinparam ActorBackgroundColor transparent

participant "Administrator" as A
participant "Log Management" as LM
participant "Authentication Management" as AM
participant "Role Management" as RM
participant "Logs" as DB
participant "RBAC role" as RBAC


activate A
activate RM
activate AM
activate RBAC
activate DB
activate LM

A -> A : Enter credentials
A -> LM : View logs
LM -> AM : Authenticate
AM -> AM : SSO
AM -> LM : Authenticated
LM -> A : Success
A -> LM : View logs
LM -> RM : Verify privledges
RM -> RBAC : Get user priveledges
RBAC -> RM : Return user privledges
RM -> RM : Verify
RM -> LM : Success
LM -> DB : Get logs
DB -> LM : Return logs
LM -> A : Return logs

deactivate A
deactivate RM
deactivate RBAC
deactivate DB
deactivate LM





@enduml